[package]
edition.workspace = true
license.workspace = true
name = "clawden-config"
version.workspace = true

[dependencies]
clawden-core = {path = "../clawden-core"}
dotenvy.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
