[package]
edition.workspace = true
license.workspace = true
name = "clawden-cli"
version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
reqwest.workspace = true
serde_json.workspace = true
