[package]
edition.workspace = true
license.workspace = true
name = "clawden-cli"
version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
clawden-adapters = {path = "../clawden-adapters"}
clawden-core = {path = "../clawden-core"}
tokio.workspace = true
